SIMPLE_INVOICE_TEMPLATES = [
    {
        "template_name": "CI INFOTECH PVT. LTD",
        "keywords": ["CI INFOTECH PVT. LTD", "07AAACC5358G1ZR", "C I Infotech Pvt Ltd"],
        "fields": {
            "company_name": {"parser": "regex", "regex": "", "type": ""},
            "company_state": {"parser": "regex", "regex": "", "type": ""},
            "company_state_cd": {"parser": "regex", "regex": "", "type": ""},
            "company_gst": {"parser": "regex", "regex": "", "type": ""},
            "vendor_gst": {"parser": "regex", "regex": "GSTIN Number : \d{2}[A-Z]{5}\d{4}[A-Z]{1}[A-Z\d]{1}[Z]{1}[A-Z\d]{1}", "type": ""},
            "vendor_name": {"parser": "regex", "regex": "", "type": ""},
            "vendor_state": {"parser": "regex", "regex": "", "type": ""},
            "vendor_state_code": {
                "parser": "regex",
                "regex": "",
                "type": "",
            },
            "invoice_date": {
                "parser": "regex",
                "regex": "tnvoice Date : (3[01]|[12][0-9]|0[1-9])\/(1[0-2]|0[1-9])\/[0-9]{4}",
                "type": "",
            },
            "invoice_no": {
                "parser": "regex",
                "regex": "Invoice Serial Number ; [a-zA-Z]{3}[0-9]{2}\/[0-9]{3}",
                "type": "",
            },
            "po_no": {"parser": "regex", "regex": "PO_NO_\d+_DT_(\d+.){3}", "type": ""},
            "sgst_rate": {"parser": "regex", "regex": "", "type": ""},
            "sgst_amount": {"parser": "regex", "regex": "", "type": ""},
            "cgst_rate": {"parser": "regex", "regex": "", "type": ""},
            "cgst_amount": {"parser": "regex", "regex": "", "type": ""},
            "igst_rate": {"parser": "regex", "regex": "\| \d*\.?\d* \d*\.?\d* \d*\.?\d* \d*\.?\d* \d*\.?\d*", "type": ""},
            "igst_amount": {"parser": "regex", "regex": "", "type": ""},
            "basic_amount": {"parser": "regex", "regex": "\d*\.?\d* \d*,\d+\.?\d* \| \d*\,?\d*\)", "type": ""},
            "total_amount": {"parser": "regex", "regex": "", "type": ""},
            "tbl_description": {"parser": "regex", "regex": "", "type": ""},
            "tbl_hsn_code": {"parser": "regex", "regex": "", "type": "0"},
            "tbl_qty": {"parser": "regex", "regex": "", "type": ""},
            "tbl_unit": {"parser": "regex", "regex": "", "type": ""},
            "tbl_rate": {"parser": "regex", "regex": "", "type": ""},
            "tble_cgst_amount": {"parser": "regex", "regex": "", "type": "0"},
            "tble_cgst_rate": {"parser": "regex", "regex": "", "type": ""},
            "tble_sgst_amount": {"parser": "regex", "regex": "", "type": ""},
            "tble_sgst_rate": {"parser": "regex", "regex": "", "type": ""},
            "tble_igst_amount": {"parser": "regex", "regex": "", "type": ""},
            "tble_igst_rate": {"parser": "regex", "regex": "", "type": ""},
            "tbl_amount": {
                "parser": "regex",
                "regex": "",
                "type": "",
            },
            "result": {"parser": "regex", "regex": "", "type": ""},
            "file_path": {"parser": "regex", "regex": "", "type": ""},
            "has_error": {"parser": "regex", "regex": "", "type": ""},
            "error": {"parser": "regex", "regex": "", "type": ""},
        },
    },
    {
        "template_name": "Astrea IT Services Private Limited",
        "keywords": ["Astrea IT Services Private Limited", "09 AAJCA3001H1Z2", ""],
        "fields": {
            "company_name": {"parser": "regex", "regex": "", "type": ""},
            "company_state": {"parser": "regex", "regex": "", "type": ""},
            "company_state_cd": {"parser": "regex", "regex": "GSTIN: \d{2}", "type": ""},
            "company_gst": {"parser": "regex", "regex": "GSTIN: \d{2} [A-Z]{5}\d{4}[A-Z]{1}[A-Z\d]{1}[Z]{1}[A-Z\d]{1}", "type": ""},
            "vendor_gst": {"parser": "regex", "regex": "GST No: \d{2}[A-Z]{5}\d{4}[A-Z]{1}[A-Z\d]{1}[Z]{1}[A-Z\d]{1}", "type": ""},
            "vendor_name": {"parser": "regex", "regex": "", "type": ""},
            "vendor_state": {"parser": "regex", "regex": "", "type": ""},
            "vendor_state_code": {
                "parser": "regex",
                "regex": "GST No: \d{2}",
                "type": "",
            },
            "invoice_date": {
                "parser": "regex",
                "regex": "Dated: [a-zA-z]+ \d\*' \d{4}",
                "type": "",
            },
            "invoice_no": {
                "parser": "regex",
                "regex": "Invoice No.: \d+- [0-9]{4}\/[0-9]{3}",
                "type": "",
            },
            "po_no": {"parser": "regex", "regex": "PO Number -\d+ Dated \d{2}.\d{2}.\d{4}", "type": "str"},
            "sgst_rate": {"parser": "regex", "regex": "SGST @ \d+%", "type": "str"},
            "sgst_amount": {"parser": "regex", "regex": "", "type": ""},
            "cgst_rate": {"parser": "regex", "regex": "CGST @ \d+%", "type": ""},
            "cgst_amount": {"parser": "regex", "regex": "", "type": ""},
            "igst_rate": {"parser": "regex", "regex": "", "type": ""},
            "igst_amount": {"parser": "regex", "regex": "", "type": ""},
            "basic_amount": {"parser": "regex", "regex": "", "type": ""},
            "total_amount": {"parser": "regex", "regex": "Rs (\d{1,2})(,\d{2})*(,\d{1,3}){1}(\.\d{1,})", "type": ""},
            "tbl_description": {"parser": "regex", "regex": "", "type": ""},
            "tbl_hsn_code": {"parser": "regex", "regex": "", "type": "0"},
            "tbl_qty": {"parser": "regex", "regex": "", "type": ""},
            "tbl_unit": {"parser": "regex", "regex": "", "type": ""},
            "tbl_rate": {"parser": "regex", "regex": "", "type": ""},
            "tble_cgst_amount": {"parser": "regex", "regex": "", "type": "0"},
            "tble_cgst_rate": {"parser": "regex", "regex": "", "type": ""},
            "tble_sgst_amount": {"parser": "regex", "regex": "", "type": ""},
            "tble_sgst_rate": {"parser": "regex", "regex": "", "type": ""},
            "tble_igst_amount": {"parser": "regex", "regex": "", "type": ""},
            "tble_igst_rate": {"parser": "regex", "regex": "", "type": ""},
            "tbl_amount": {
                "parser": "regex",
                "regex": "",
                "type": "",
            },
            "result": {"parser": "regex", "regex": "", "type": ""},
            "file_path": {"parser": "regex", "regex": "", "type": ""},
            "has_error": {"parser": "regex", "regex": "", "type": ""},
            "error": {"parser": "regex", "regex": "", "type": ""},
        },
    },
]



FITZ_INVOICE_TEMPLATE = [
    {
        "template_name": "Motherson Automotive Technologies & Engineering",
        "keywords": [
            "Motherson Automotive Technologies & Engineering",
            "09AAACM0405A1ZB",
        ],
        "fields": {
            "0-0-0-1": {"name": "Company Name", "key": "company_name", "value": "Motherson Automotive Technologies & Engineering"},
            "0-0-0-2": {
                "name": "Company State Code",
                "key": "company_state_cd",
                "value": "",
            },
            "0-0-0-3": {"name": "Company State", "key": "company_state", "value": ""},
            "0-0-0-4": {"name": "Vendor Name", "key": "vendor_name", "value": ""},
            "0-0-0-5": {"name": "Vendor State", "key": "vendor_state", "value": ""},
            "0-0-0-6": {
                "name": "Vendor State Code",
                "key": "vendor_state_code",
                "value": "",
            },
            "2-0-0": {"name": "Invoice Date", "key": "invoice_date", "value": ""},
            "2-1-0": {"name": "Invoice No.", "key": "invoice_no", "value": ""},
            "1-1-0": {"name": "PO No.", "key": "po_no", "value": ""},
            "29-5-0": {"name": "SGST Rate", "key": "sgst_rate", "value": "0"},
            "0-0-0-7": {"name": "SGST Amount.", "key": "sgst_amount", "value": "0"},
            "29-4-0": {"name": "CGST Rate", "key": "cgst_rate", "value": "0"},
            "0-0-0-8": {"name": "CGST Amount", "key": "cgst_amount", "value": "0"},
            "29-7-0": {"name": "IGST Rate.", "key": "igst_rate", "value": "18%"},
            "70-0-0": {"name": "IGST Amount", "key": "igst_amount", "value": ""},
            "73-0-0": {"name": "Basic Amount", "key": "basic_amount", "value": ""},
            "31-0-0": {"name": "Total Amount", "key": "total_amount", "value": ""},
            "0-0-0-9": {
                "name": "TBL Description.",
                "key": "tbl_description",
                "value": "",
            },
            "0-0-0-10": {"name": "TBL HSN Code", "key": "tbl_hsn_code", "value": "0"},
            "0-0-0-11": {"name": "TBL Quantity", "key": "tbl_qty", "value": "0"},
            "0-0-0-12": {"name": "TBL Unit", "key": "tbl_unit", "value": "0"},
            "0-0-0-13": {"name": "TBL Rate", "key": "tbl_rate", "value": "0"},
            "0-0-0-14": {
                "name": "TBL CGST Amount",
                "key": "tble_cgst_amount",
                "value": "0",
            },
            "0-0-0-15": {"name": "TBLE CGST Rate", "key": "tble_cgst_rate", "value": "0"},
            "0-0-0-16": {
                "name": "TBLE SGST Amount",
                "key": "tble_sgst_amount",
                "value": "0",
            },
            "0-0-0-17": {"name": "TBLE SGST Rate", "key": "tble_sgst_rate", "value": "0"},
            "0-0-0-18": {
                "name": "TBLE IGST Amount",
                "key": "tble_igst_amount",
                "value": "0",
            },
            "0-0-0-19": {"name": "TBLE IGST Rate", "key": "tble_igst_rate", "value": "0"},
            "0-0-0-20": {"name": "TBL Amount", "key": "tbl_amount", "value": "0"},
            "18-0-2": {"name": "Company GST Number", "key": "company_gst", "value": ""},
            "17-0-0": {"name": "Vendor GST Number", "key": "vendor_gst", "value": ""},
        },
    }
]
