# Generated by Django 4.0.6 on 2022-12-07 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('company_state', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('company_state_cd', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('vendor_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('vendor_state', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('vendor_state_code', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('invoice_date', models.DateField(blank=True, default=None, null=True)),
                ('invoice_no', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('po_no', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('sgst_rate', models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=10, null=True)),
                ('sgst_amount', models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=10, null=True)),
                ('cgst_rate', models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=10, null=True)),
                ('cgst_amount', models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=10, null=True)),
                ('igst_rate', models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=10, null=True)),
                ('igst_amount', models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=10, null=True)),
                ('basic_amount', models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=10, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=10, null=True)),
                ('tbl_description', models.TextField(blank=True)),
                ('tbl_hsn_code', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('tbl_qty', models.IntegerField(blank=True, default=None, null=True)),
                ('tbl_unit', models.IntegerField(blank=True, default=None, null=True)),
                ('tbl_rate', models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=10, null=True)),
                ('tble_cgst_amount', models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=10, null=True)),
                ('tble_cgst_rate', models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=10, null=True)),
                ('tble_sgst_amount', models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=10, null=True)),
                ('tble_sgst_rate', models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=10, null=True)),
                ('tble_igst_amount', models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=10, null=True)),
                ('tble_igst_rate', models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=10, null=True)),
                ('tbl_amount', models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=10, null=True)),
                ('result', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('file_path', models.FileField(blank=True, upload_to='')),
                ('has_error', models.BooleanField(blank=True, default=False)),
                ('error', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
