# Generated by Django 4.0.6 on 2022-12-09 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_invoicefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='company_gst',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='vendor_gst',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
