# Generated by Django 4.0.6 on 2022-12-09 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_invoice_company_gst_invoice_vendor_gst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_date',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
